#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AppAndroid.Resource", IsApplication=true)]

namespace AppAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::AppAndroid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::AppAndroid.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int colorSpinner = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Bus = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bus_blank_back = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bus_blank_front = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bus_blank_left = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bus_blank_right = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bus_droit = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int circle_green = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int CircleT = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Logo = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Logo_SITUS = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Splash = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Square = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int square_blue = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int trash = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int triangle_red = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int TriangleT = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070023
			public const int HeadTableHistIncCond = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int HeadTableHistIncMaJ = 2131165220;
			
			// aapt resource value: 0x7f070021
			public const int HeadTableHistIncNum = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int HeadTableHistIncObs = 2131165218;
			
			// aapt resource value: 0x7f070042
			public const int LaunchButtonDB1 = 2131165250;
			
			// aapt resource value: 0x7f070043
			public const int LaunchButtonDB2 = 2131165251;
			
			// aapt resource value: 0x7f070044
			public const int LaunchButtonDB3 = 2131165252;
			
			// aapt resource value: 0x7f070045
			public const int LaunchButtonDB4 = 2131165253;
			
			// aapt resource value: 0x7f070046
			public const int LaunchButtonDB5 = 2131165254;
			
			// aapt resource value: 0x7f070049
			public const int LaunchButtonDB6 = 2131165257;
			
			// aapt resource value: 0x7f07004a
			public const int LaunchButtonDB7 = 2131165258;
			
			// aapt resource value: 0x7f07004b
			public const int LaunchButtonDB8 = 2131165259;
			
			// aapt resource value: 0x7f07004c
			public const int LaunchButtonDB9 = 2131165260;
			
			// aapt resource value: 0x7f07001e
			public const int LinearLayoutHistInc = 2131165214;
			
			// aapt resource value: 0x7f070050
			public const int ResultTextDB = 2131165264;
			
			// aapt resource value: 0x7f070020
			public const int TableLayoutHistInc = 2131165216;
			
			// aapt resource value: 0x7f07004d
			public const int TestProgressBarDB = 2131165261;
			
			// aapt resource value: 0x7f07004e
			public const int TextBoxDB = 2131165262;
			
			// aapt resource value: 0x7f070026
			public const int bus_blank_back = 2131165222;
			
			// aapt resource value: 0x7f070028
			public const int bus_blank_front = 2131165224;
			
			// aapt resource value: 0x7f070025
			public const int bus_blank_left = 2131165221;
			
			// aapt resource value: 0x7f070027
			public const int bus_blank_right = 2131165223;
			
			// aapt resource value: 0x7f07003c
			public const int button1 = 2131165244;
			
			// aapt resource value: 0x7f070003
			public const int buttonAddAdminBus = 2131165187;
			
			// aapt resource value: 0x7f07000b
			public const int buttonAddModelAdminBus = 2131165195;
			
			// aapt resource value: 0x7f07003b
			public const int buttonDB = 2131165243;
			
			// aapt resource value: 0x7f07003a
			public const int buttonDD = 2131165242;
			
			// aapt resource value: 0x7f070009
			public const int buttonDeleteAdminBus = 2131165193;
			
			// aapt resource value: 0x7f070015
			public const int buttonDeleteAdminConduc = 2131165205;
			
			// aapt resource value: 0x7f07001d
			public const int buttonDeleteAdminContro = 2131165213;
			
			// aapt resource value: 0x7f07000f
			public const int buttonDeleteAdminModel = 2131165199;
			
			// aapt resource value: 0x7f07002b
			public const int buttonPrec = 2131165227;
			
			// aapt resource value: 0x7f07002c
			public const int buttonSuiv = 2131165228;
			
			// aapt resource value: 0x7f070008
			public const int buttonUpdateAdminBus = 2131165192;
			
			// aapt resource value: 0x7f070014
			public const int buttonUpdateAdminConduc = 2131165204;
			
			// aapt resource value: 0x7f07001c
			public const int buttonUpdateAdminContro = 2131165212;
			
			// aapt resource value: 0x7f07000e
			public const int buttonUpdateAdminModel = 2131165198;
			
			// aapt resource value: 0x7f070011
			public const int buttonValCreaConduc = 2131165201;
			
			// aapt resource value: 0x7f070018
			public const int buttonValCreaContro = 2131165208;
			
			// aapt resource value: 0x7f070035
			public const int buttonValidateInci = 2131165237;
			
			// aapt resource value: 0x7f07002f
			public const int checkBoxInci = 2131165231;
			
			// aapt resource value: 0x7f07000a
			public const int editTextAddModel = 2131165194;
			
			// aapt resource value: 0x7f070000
			public const int editTextAddNumeroBus = 2131165184;
			
			// aapt resource value: 0x7f070017
			public const int editTextMdPCreaContro = 2131165207;
			
			// aapt resource value: 0x7f070010
			public const int editTextNomCreaConduc = 2131165200;
			
			// aapt resource value: 0x7f070016
			public const int editTextNomCreaContro = 2131165206;
			
			// aapt resource value: 0x7f07001b
			public const int editTextUpdateMdpContro = 2131165211;
			
			// aapt resource value: 0x7f07000d
			public const int editTextUpdateModel = 2131165197;
			
			// aapt resource value: 0x7f070013
			public const int editTextUpdateNameConduc = 2131165203;
			
			// aapt resource value: 0x7f07001a
			public const int editTextUpdateNameContro = 2131165210;
			
			// aapt resource value: 0x7f070005
			public const int editTextUpdateNumeroBus = 2131165189;
			
			// aapt resource value: 0x7f070040
			public const int horizontalScrollView1 = 2131165248;
			
			// aapt resource value: 0x7f070047
			public const int horizontalScrollView2 = 2131165255;
			
			// aapt resource value: 0x7f070036
			public const int imageView1 = 2131165238;
			
			// aapt resource value: 0x7f070030
			public const int imgCircle = 2131165232;
			
			// aapt resource value: 0x7f070031
			public const int imgSquare = 2131165233;
			
			// aapt resource value: 0x7f070034
			public const int imgTrash = 2131165236;
			
			// aapt resource value: 0x7f070032
			public const int imgTriangle = 2131165234;
			
			// aapt resource value: 0x7f070041
			public const int linearLayout1 = 2131165249;
			
			// aapt resource value: 0x7f070048
			public const int linearLayout2 = 2131165256;
			
			// aapt resource value: 0x7f07003f
			public const int listBus = 2131165247;
			
			// aapt resource value: 0x7f07003d
			public const int listViewLeftMenu = 2131165245;
			
			// aapt resource value: 0x7f07002e
			public const int lyBottom = 2131165230;
			
			// aapt resource value: 0x7f07002d
			public const int lyMiddle = 2131165229;
			
			// aapt resource value: 0x7f070029
			public const int lyTop = 2131165225;
			
			// aapt resource value: 0x7f07004f
			public const int scrollViewDB = 2131165263;
			
			// aapt resource value: 0x7f07001f
			public const int scrollViewhi = 2131165215;
			
			// aapt resource value: 0x7f070039
			public const int spinner1 = 2131165241;
			
			// aapt resource value: 0x7f070002
			public const int spinnerColorAdminBus = 2131165186;
			
			// aapt resource value: 0x7f070033
			public const int spinnerGravity = 2131165235;
			
			// aapt resource value: 0x7f070001
			public const int spinnerModelAdminBus = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int spinnerSelectAdminBus = 2131165188;
			
			// aapt resource value: 0x7f070012
			public const int spinnerSelectAdminConduc = 2131165202;
			
			// aapt resource value: 0x7f070019
			public const int spinnerSelectAdminContro = 2131165209;
			
			// aapt resource value: 0x7f07000c
			public const int spinnerSelectAdminModel = 2131165196;
			
			// aapt resource value: 0x7f070007
			public const int spinnerUpdateColorAdminBus = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int spinnerUpdateModelAdminBus = 2131165190;
			
			// aapt resource value: 0x7f070037
			public const int textView1 = 2131165239;
			
			// aapt resource value: 0x7f070038
			public const int textView2 = 2131165240;
			
			// aapt resource value: 0x7f07003e
			public const int textViewBus = 2131165246;
			
			// aapt resource value: 0x7f07002a
			public const int txtNumBus = 2131165226;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CreaBus = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CreaConduc = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CreaContro = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int HistIncident = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int IChoicePart = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int lCheckup = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Menu = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int TestDB = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
