#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AppAndroid.Resource", IsApplication=true)]

namespace AppAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::AppAndroid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::AppAndroid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Bus = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bus_blank_back = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bus_blank_front = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bus_blank_left = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bus_blank_right = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bus_droit = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int circle_green = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Logo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Logo_SITUS = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int square_blue = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int trash = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int triangle_red = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050029
			public const int LaunchButtonDB1 = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int LaunchButtonDB2 = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int LaunchButtonDB3 = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int LaunchButtonDB4 = 2131034156;
			
			// aapt resource value: 0x7f05002d
			public const int LaunchButtonDB5 = 2131034157;
			
			// aapt resource value: 0x7f050030
			public const int LaunchButtonDB6 = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int LaunchButtonDB7 = 2131034161;
			
			// aapt resource value: 0x7f050032
			public const int LaunchButtonDB8 = 2131034162;
			
			// aapt resource value: 0x7f050033
			public const int LaunchButtonDB9 = 2131034163;
			
			// aapt resource value: 0x7f050008
			public const int LinearLayoutHistInc = 2131034120;
			
			// aapt resource value: 0x7f050037
			public const int ResultTextDB = 2131034167;
			
			// aapt resource value: 0x7f05000a
			public const int TableLayoutHistInc = 2131034122;
			
			// aapt resource value: 0x7f050034
			public const int TestProgressBarDB = 2131034164;
			
			// aapt resource value: 0x7f050035
			public const int TextBoxDB = 2131034165;
			
			// aapt resource value: 0x7f05000c
			public const int bus_blank_back = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int bus_blank_front = 2131034126;
			
			// aapt resource value: 0x7f05000b
			public const int bus_blank_left = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int bus_blank_right = 2131034125;
			
			// aapt resource value: 0x7f050023
			public const int button1 = 2131034147;
			
			// aapt resource value: 0x7f050022
			public const int buttonDB = 2131034146;
			
			// aapt resource value: 0x7f050002
			public const int buttonValCreaBus = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int buttonValCreaConduc = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int buttonValCreaContro = 2131034119;
			
			// aapt resource value: 0x7f05001d
			public const int buttonValidate = 2131034141;
			
			// aapt resource value: 0x7f050006
			public const int editTextMdPCreaContro = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int editTextNomCreaConduc = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int editTextNomCreaContro = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int editTextNumeroBus = 2131034112;
			
			// aapt resource value: 0x7f050027
			public const int horizontalScrollView1 = 2131034151;
			
			// aapt resource value: 0x7f05002e
			public const int horizontalScrollView2 = 2131034158;
			
			// aapt resource value: 0x7f05001e
			public const int imageView1 = 2131034142;
			
			// aapt resource value: 0x7f050012
			public const int imgBus = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int imgCircle = 2131034132;
			
			// aapt resource value: 0x7f050016
			public const int imgSquare = 2131034134;
			
			// aapt resource value: 0x7f050018
			public const int imgTriangle = 2131034136;
			
			// aapt resource value: 0x7f05001a
			public const int imgtrash = 2131034138;
			
			// aapt resource value: 0x7f050028
			public const int linearLayout1 = 2131034152;
			
			// aapt resource value: 0x7f05002f
			public const int linearLayout2 = 2131034159;
			
			// aapt resource value: 0x7f050026
			public const int listBus = 2131034150;
			
			// aapt resource value: 0x7f050024
			public const int listViewLeftMenu = 2131034148;
			
			// aapt resource value: 0x7f050013
			public const int lyBottom = 2131034131;
			
			// aapt resource value: 0x7f050011
			public const int lyMiddle = 2131034129;
			
			// aapt resource value: 0x7f05000f
			public const int lyTop = 2131034127;
			
			// aapt resource value: 0x7f050036
			public const int scrollViewDB = 2131034166;
			
			// aapt resource value: 0x7f050009
			public const int scrollViewhi = 2131034121;
			
			// aapt resource value: 0x7f050021
			public const int spinner1 = 2131034145;
			
			// aapt resource value: 0x7f050001
			public const int spinnerColorCreaBus = 2131034113;
			
			// aapt resource value: 0x7f05001f
			public const int textView1 = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int textView2 = 2131034144;
			
			// aapt resource value: 0x7f050025
			public const int textViewBus = 2131034149;
			
			// aapt resource value: 0x7f05001b
			public const int txtController = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int txtDriver = 2131034140;
			
			// aapt resource value: 0x7f050019
			public const int txtIncidHigh = 2131034137;
			
			// aapt resource value: 0x7f050015
			public const int txtIncidLow = 2131034133;
			
			// aapt resource value: 0x7f050017
			public const int txtIncidMedium = 2131034135;
			
			// aapt resource value: 0x7f050010
			public const int txtNumBus = 2131034128;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CreaBus = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CreaConduc = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CreaContro = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int HistIncident = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int IChoicePart = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int lCheckup = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Menu = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int TestDB = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
