#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AppAndroid.Resource", IsApplication=true)]

namespace AppAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::AppAndroid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::AppAndroid.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int colorSpinner = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Bus = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bus_blank_back = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bus_blank_front = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bus_blank_left = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bus_blank_right = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bus_droit = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int circle_green = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int CircleT = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Logo = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Logo_SITUS = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Square = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int square_blue = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int trash = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int triangle_red = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int TriangleT = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060023
			public const int HeadTableHistIncCond = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int HeadTableHistIncMaJ = 2131099684;
			
			// aapt resource value: 0x7f060021
			public const int HeadTableHistIncNum = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int HeadTableHistIncObs = 2131099682;
			
			// aapt resource value: 0x7f060042
			public const int LaunchButtonDB1 = 2131099714;
			
			// aapt resource value: 0x7f060043
			public const int LaunchButtonDB2 = 2131099715;
			
			// aapt resource value: 0x7f060044
			public const int LaunchButtonDB3 = 2131099716;
			
			// aapt resource value: 0x7f060045
			public const int LaunchButtonDB4 = 2131099717;
			
			// aapt resource value: 0x7f060046
			public const int LaunchButtonDB5 = 2131099718;
			
			// aapt resource value: 0x7f060049
			public const int LaunchButtonDB6 = 2131099721;
			
			// aapt resource value: 0x7f06004a
			public const int LaunchButtonDB7 = 2131099722;
			
			// aapt resource value: 0x7f06004b
			public const int LaunchButtonDB8 = 2131099723;
			
			// aapt resource value: 0x7f06004c
			public const int LaunchButtonDB9 = 2131099724;
			
			// aapt resource value: 0x7f06001e
			public const int LinearLayoutHistInc = 2131099678;
			
			// aapt resource value: 0x7f060050
			public const int ResultTextDB = 2131099728;
			
			// aapt resource value: 0x7f060020
			public const int TableLayoutHistInc = 2131099680;
			
			// aapt resource value: 0x7f06004d
			public const int TestProgressBarDB = 2131099725;
			
			// aapt resource value: 0x7f06004e
			public const int TextBoxDB = 2131099726;
			
			// aapt resource value: 0x7f060026
			public const int bus_blank_back = 2131099686;
			
			// aapt resource value: 0x7f060028
			public const int bus_blank_front = 2131099688;
			
			// aapt resource value: 0x7f060025
			public const int bus_blank_left = 2131099685;
			
			// aapt resource value: 0x7f060027
			public const int bus_blank_right = 2131099687;
			
			// aapt resource value: 0x7f06003c
			public const int button1 = 2131099708;
			
			// aapt resource value: 0x7f060003
			public const int buttonAddAdminBus = 2131099651;
			
			// aapt resource value: 0x7f06000b
			public const int buttonAddModelAdminBus = 2131099659;
			
			// aapt resource value: 0x7f06003b
			public const int buttonDB = 2131099707;
			
			// aapt resource value: 0x7f06003a
			public const int buttonDD = 2131099706;
			
			// aapt resource value: 0x7f060009
			public const int buttonDeleteAdminBus = 2131099657;
			
			// aapt resource value: 0x7f060015
			public const int buttonDeleteAdminConduc = 2131099669;
			
			// aapt resource value: 0x7f06001d
			public const int buttonDeleteAdminContro = 2131099677;
			
			// aapt resource value: 0x7f06000f
			public const int buttonDeleteAdminModel = 2131099663;
			
			// aapt resource value: 0x7f06002b
			public const int buttonPrec = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int buttonSuiv = 2131099692;
			
			// aapt resource value: 0x7f060008
			public const int buttonUpdateAdminBus = 2131099656;
			
			// aapt resource value: 0x7f060014
			public const int buttonUpdateAdminConduc = 2131099668;
			
			// aapt resource value: 0x7f06001c
			public const int buttonUpdateAdminContro = 2131099676;
			
			// aapt resource value: 0x7f06000e
			public const int buttonUpdateAdminModel = 2131099662;
			
			// aapt resource value: 0x7f060011
			public const int buttonValCreaConduc = 2131099665;
			
			// aapt resource value: 0x7f060018
			public const int buttonValCreaContro = 2131099672;
			
			// aapt resource value: 0x7f060035
			public const int buttonValidateInci = 2131099701;
			
			// aapt resource value: 0x7f06002f
			public const int checkBoxInci = 2131099695;
			
			// aapt resource value: 0x7f06000a
			public const int editTextAddModel = 2131099658;
			
			// aapt resource value: 0x7f060000
			public const int editTextAddNumeroBus = 2131099648;
			
			// aapt resource value: 0x7f060017
			public const int editTextMdPCreaContro = 2131099671;
			
			// aapt resource value: 0x7f060010
			public const int editTextNomCreaConduc = 2131099664;
			
			// aapt resource value: 0x7f060016
			public const int editTextNomCreaContro = 2131099670;
			
			// aapt resource value: 0x7f06001b
			public const int editTextUpdateMdpContro = 2131099675;
			
			// aapt resource value: 0x7f06000d
			public const int editTextUpdateModel = 2131099661;
			
			// aapt resource value: 0x7f060013
			public const int editTextUpdateNameConduc = 2131099667;
			
			// aapt resource value: 0x7f06001a
			public const int editTextUpdateNameContro = 2131099674;
			
			// aapt resource value: 0x7f060005
			public const int editTextUpdateNumeroBus = 2131099653;
			
			// aapt resource value: 0x7f060040
			public const int horizontalScrollView1 = 2131099712;
			
			// aapt resource value: 0x7f060047
			public const int horizontalScrollView2 = 2131099719;
			
			// aapt resource value: 0x7f060036
			public const int imageView1 = 2131099702;
			
			// aapt resource value: 0x7f060030
			public const int imgCircle = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int imgSquare = 2131099697;
			
			// aapt resource value: 0x7f060034
			public const int imgTrash = 2131099700;
			
			// aapt resource value: 0x7f060032
			public const int imgTriangle = 2131099698;
			
			// aapt resource value: 0x7f060041
			public const int linearLayout1 = 2131099713;
			
			// aapt resource value: 0x7f060048
			public const int linearLayout2 = 2131099720;
			
			// aapt resource value: 0x7f06003f
			public const int listBus = 2131099711;
			
			// aapt resource value: 0x7f06003d
			public const int listViewLeftMenu = 2131099709;
			
			// aapt resource value: 0x7f06002e
			public const int lyBottom = 2131099694;
			
			// aapt resource value: 0x7f06002d
			public const int lyMiddle = 2131099693;
			
			// aapt resource value: 0x7f060029
			public const int lyTop = 2131099689;
			
			// aapt resource value: 0x7f06004f
			public const int scrollViewDB = 2131099727;
			
			// aapt resource value: 0x7f06001f
			public const int scrollViewhi = 2131099679;
			
			// aapt resource value: 0x7f060039
			public const int spinner1 = 2131099705;
			
			// aapt resource value: 0x7f060002
			public const int spinnerColorAdminBus = 2131099650;
			
			// aapt resource value: 0x7f060033
			public const int spinnerGravity = 2131099699;
			
			// aapt resource value: 0x7f060001
			public const int spinnerModelAdminBus = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int spinnerSelectAdminBus = 2131099652;
			
			// aapt resource value: 0x7f060012
			public const int spinnerSelectAdminConduc = 2131099666;
			
			// aapt resource value: 0x7f060019
			public const int spinnerSelectAdminContro = 2131099673;
			
			// aapt resource value: 0x7f06000c
			public const int spinnerSelectAdminModel = 2131099660;
			
			// aapt resource value: 0x7f060007
			public const int spinnerUpdateColorAdminBus = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int spinnerUpdateModelAdminBus = 2131099654;
			
			// aapt resource value: 0x7f060037
			public const int textView1 = 2131099703;
			
			// aapt resource value: 0x7f060038
			public const int textView2 = 2131099704;
			
			// aapt resource value: 0x7f06003e
			public const int textViewBus = 2131099710;
			
			// aapt resource value: 0x7f06002a
			public const int txtNumBus = 2131099690;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CreaBus = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CreaConduc = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CreaContro = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int HistIncident = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int IChoicePart = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int lCheckup = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Menu = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int TestDB = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
